name: Linux amd64 (test build)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: clay-pve

    strategy:
      matrix:
        defines:
          - ""

    env:
      UPLOAD_ARTIFACT: "true"
      IMAGE_TAG: tdesktop:centos_env

    steps:
      - name: Check out
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Prepare for build
        run: |
          cd Telegram/build/docker/centos_env
          poetry install
          poetry run gen_dockerfile | DOCKER_BUILDKIT=1 docker build -t ${{ env.IMAGE_TAG }} -

      - name: Build
        run: |
          DEFINE=""
          if [ -n "${{ matrix.defines }}" ]; then
            DEFINE="-D ${{ matrix.defines }}=ON"
            echo Define from matrix: $DEFINE
            echo "ARTIFACT_NAME=MayuGram ${{ matrix.defines }}" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=MayuGram" >> $GITHUB_ENV
          fi

          docker run --rm \
          -u $(id -u) \
          -v $PWD:/usr/src/tdesktop \
          -e CONFIG=Debug \
          -e CCACHE_SLOPPINESS=pch_defines,time_macros \
          $IMAGE_TAG \
          /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
          -D CMAKE_CONFIGURATION_TYPES=Debug \
          -D CMAKE_C_FLAGS_DEBUG="-O0 -fpch-preprocess" \
          -D CMAKE_CXX_FLAGS_DEBUG="-O0 -fpch-preprocess" \
          -D TDESKTOP_API_TEST=ON \
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=ON \
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=OFF \
          $DEFINE

      - name: Check if build completed successfully
        run: |
          filePath="out/Debug/Telegram"
          if test -f "$filePath"; then
            echo "Build successfully done! :)"

            size=$(stat -c %s "$filePath")
            echo "File size of ${filePath}: ${size} Bytes."
          else
            echo "Build error, output file does not exist."
            exit 1
          fi

      - name: Upload artifacts
        run: |
          cd out/Debug
          mkdir artifact
          mv {Telegram,Updater} artifact/

          fileName="${ARTIFACT_NAME}-$(date +%Y-%m-%d)-linux.zip"
          zip -r "${fileName}" artifact/
          sudo mv "${fileName}" /var/www/mayu
          sudo chown caddy:caddy "/var/www/mayu/${fileName}"
          sudo chmod 644 "/var/www/mayu/${fileName}"
